version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "library-db"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
    ports:
      - "5432:5432"

  library:
    image: library-image
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - 5220:5220
    depends_on:
       - "postgres"

